[netfilter-rules] Update scripts
Signed-off-by: babykart <babykart@gmail.com>

diff --git a/netfilter-rules b/netfilter-rules
--- a/netfilter-rules
+++ b/netfilter-rules
@@ -8,26 +8,27 @@
 # Updated by Stephane Malinet 20140531 (v3.2)
 # Updated by Stephane Malinet 20140602 (v3.2.1)
 # Updated by Stephane Malinet 20250330 (v3.3.0)
+# Updated by Stephane Malinet 20250330 (v3.3.1)
 
 IPT="$(command -v iptables)"
-IPT_CONF="/etc/netfilter-rules.conf"
-IPT_CONF_DIR="/etc/netfilter-rules.d"
+NF_CONF="/etc/netfilter-rules.conf"
+NF_CONF_DIR="/etc/netfilter-rules.d"
 
 source_conf_file() {
-  [ ! -f "${IPT_CONF}" ] && {
-    echo "${IPT_CONF} missing" 1>&2
+  [ ! -f "${NF_CONF}" ] && {
+    echo "${NF_CONF} missing" 1>&2
     exit 1
   }
-  source "${IPT_CONF}"
+  source "${NF_CONF}"
 }
 
 run_extra_cmds() {
-  [ ! -d "${IPT_CONF_DIR}" ] && {
-    echo "${IPT_CONF_DIR} directory missing" 1>&2
+  [ ! -d "${NF_CONF_DIR}" ] && {
+    echo "${NF_CONF_DIR} directory missing" 1>&2
     exit 1
   }
   local extra_cmds extra_cmd
-  extra_cmds="$(find ${IPT_CONF_DIR} -type f -name '*.rule')"
+  extra_cmds="$(find ${NF_CONF_DIR} -type f -name '*.rule')"
   for extra_cmd in ${extra_cmds} ; do
     . ${extra_cmd}
   done
@@ -59,20 +60,24 @@ case "${1}" in
     ${IPT} -t filter -A LOGDROP -j LOG --log-prefix "[DROP] "
     ${IPT} -t filter -A LOGDROP -j REJECT
 
+    local int
     for int in ${ping} ; do
       ${IPT} -A INPUT -p ICMP -i ${int} -j ACCEPT
     done
 
+    local except
     for except in ${exceptions} ; do
       ${IPT} -t filter -A INPUT -s ${except} -j ACCEPT
     done
 
+    local int_all
     for int_all in ${all} ; do
       ${IPT} -t filter -A INPUT -i ${int_all} -j ACCEPT
     done
 
     OLDIFS=$IFS
 
+    local int_t tcpint
     for int_t in ${tcpint} ; do
       IFS="+"
       set -- ${int_t}
@@ -90,9 +95,10 @@ case "${1}" in
 
     IFS=$OLDIFS
 
-    for int_u in $udpint ; do
+    local int_u udpint
+    for int_u in ${udpint} ; do
       IFS="+"
-      set -- $int_u
+      set -- ${int_u}
 
       int_u=$1
       shift
